### ISSUE TITLE
Panics in `TestPrimeTestSuite/TestLocalClusterRancherImages` test

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#1027]
Config:
```
rancher:
    host: "https://ip of docker install"
    adminToken: "token-fkppx:<>"
prime:
    brand: "suse"
    isPrime: true
    registry: "registry.rancher.com"
    rancherVersion: "v2.7.9"

```
- Panic:
```
=== RUN   TestPrimeTestSuite/TestLocalClusterRancherImages
    suite.go:87: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 66 [running]:
        runtime/debug.Stack()
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
        github.com/stretchr/testify/suite.failOnPanic(0xc0001b6000, {0x1f457c0, 0x399dea0})
        	/root/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:87 +0x3b
        github.com/stretchr/testify/suite.Run.func1.1()
        	/root/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:183 +0x252
        panic({0x1f457c0, 0x399dea0})
        	/usr/local/go/src/runtime/panic.go:884 +0x213
        github.com/rancher/rancher/tests/framework/extensions/workloads/pods.StatusPods(0xc00049c270?, {0x22ca6b8?, 0x1?})
        	/root/go/src/github.com/rancher/rancher/tests/framework/extensions/workloads/pods/pod_status.go:20 +0x20
        github.com/rancher/rancher/tests/v2/validation/prime.(*PrimeTestSuite).TestLocalClusterRancherImages(0xc0000b65a0)
        	/root/go/src/github.com/rancher/rancher/tests/v2/validation/prime/prime_test.go:82 +0x35
        reflect.Value.call({0xc0004d3100?, 0xc0005ff470?, 0x13?}, {0x22c9b24, 0x4}, {0xc000717e70, 0x1, 0x1?})
        	/usr/local/go/src/reflect/value.go:586 +0xb07
        reflect.Value.Call({0xc0004d3100?, 0xc0005ff470?, 0xc0000b65a0?}, {0xc000076670?, 0x32c0cb8?, 0x28b645a?})
        	/usr/local/go/src/reflect/value.go:370 +0xbc
        github.com/stretchr/testify/suite.Run.func1(0xc0001b6000)
        	/root/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:197 +0x4b6
        testing.tRunner(0xc0001b6000, 0xc000409680)
        	/usr/local/go/src/testing/testing.go:1576 +0x10b
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1629 +0x3ea
    --- FAIL: TestPrimeTestSuite/TestLocalClusterRancherImages (0.00s)
```

**Comment by markusewalker** [comment]
Talked in offline regarding this. This is a non-issue and was due to configuration mishaps. Closing issue.
