### ISSUE TITLE
Fix go automation registry tests

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#888]
After the big provisioning refactor, the registry tests are now broken and don't run. Need to investigate what's wrong, and fix them to their previous working state.

**Comment by izaac** [comment]
```shell
=== RUN   TestRegistryTestSuite/TestRegistriesK3S
=== RUN   TestRegistryTestSuite/TestRegistriesK3S/K3S_Registry_No_Auth
--- FAIL: TestRegistryTestSuite/TestRegistriesK3S/K3S_Registry_No_Auth (0.00s)
--- FAIL: TestRegistryTestSuite/TestRegistriesK3S (1.34s)
--- FAIL: TestRegistryTestSuite (4.72s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x101c108ea]

goroutine 194 [running]:
testing.tRunner.func1.2({0x10201e1c0, 0x103eaeb80})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x10201e1c0, 0x103eaeb80})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/rancher/rancher/tests/v2/validation/provisioning/registries.(*RegistryTestSuite).configureRKE2K3SRegistry(...)
	/Users/izaac/repos/rancher-izaac-back/tests/v2/validation/provisioning/registries/registry_test.go:375
github.com/rancher/rancher/tests/v2/validation/provisioning/registries.(*RegistryTestSuite).TestRegistriesK3S.func1()
	/Users/izaac/repos/rancher-izaac-back/tests/v2/validation/provisioning/registries/registry_test.go:294 +0x1ca
github.com/stretchr/testify/suite.(*Suite).Run.func2(0x0?)
	/Users/izaac/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112 +0x36
testing.tRunner(0xc00074a000, 0xc000730018)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/rancher/rancher/tests/v2/validation/provisioning/registries	4.766s
```
